[[constraint]]
  branch = "master"
  name = "github.com/urfave/cli"

[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault"

[[constraint]]
  branch = "master"
  name = "github.com/fatih/color"
